[project]
name = "deep-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.35.0",
    "ipykernel>=6.29.5",
    "openai-agents>=0.1.0",
]
